name: Linting and API Test

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install pipenv
          pipenv install --dev
      
      - name: Run linter
        run: pipenv run flake8 .
        continue-on-error: true

      - name: Run API Tests
        run: pipenv run pytest
    
